spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: durupmailtester@gmail.com
    password: dlatlrPwjd1!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true